name: Endfield Auto Sign
on:
  schedule:
    - cron: '10 16 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false
      - name: Run endfield sign
        env:
          SKYLAND_TOKEN: ${{ secrets.SKYLAND_TOKEN }}
        run: |
          pip install requests -q
          python auto_sign.py
